CREATE OR REPLACE VIEW SCHOOL_MASTER_DATA AS
SELECT 
    SCHOOL_CODE, SCHOOL_NAME, TOWN_SUBURB, POSTCODE, 
    LGA, ASGS_REMOTENESS, AECG_REGION, LATITUDE, LONGITUDE
FROM 
    PUBLIC_SCHOOL_NSW_MASTER_DATASET;

CREATE OR REPLACE VIEW SCHOOL_ATTENDANCE_DATA AS
SELECT 
    SCHOOL_CODE, YEAR, ATTENDANCE_PCT
FROM 
    STUDENT_ATTENDANCE_UNPIVOTED;

CREATE OR REPLACE VIEW SCHOOL_COMPOSITE_DATA AS
SELECT 
    SCHOOL_CODE, SCHOOL_NAME, YEAR, 
    COMPOSITE_CLASS_COUNT, COMPOSITE_CLASS_STUDENTS, 
    PCT_COMPOSITE_CLASSES, PCT_COMPOSITE_CLASS_STUDENTS
FROM 
    MULTI_AGE_COMPOSITE_UNPIVOTED;


CREATE OR REPLACE VIEW SCHOOL_CHARACTERISTICS AS
SELECT 
    SCHOOL_CODE, LEVEL_OF_SCHOOLING, SELECTIVE_SCHOOL, OPPORTUNITY_CLASS, 
    SCHOOL_SPECIALTY_TYPE, LATEST_YEAR_ENROLMENT_FTE, INDIGENOUS_PCT, LBOTE_PCT, 
    SCHOOL_SUBTYPE, PRESCHOOL_IND, DISTANCE_EDUCATION, INTENSIVE_ENGLISH_CENTRE, 
    SCHOOL_GENDER, LATE_OPENING_SCHOOL
FROM 
    PUBLIC_SCHOOL_NSW_MASTER_DATASET;
